name = "portfolio"
compatibility_date = "2025-07-26"

# Static assets configuration
[assets]
directory = "./dist"

# Build configuration
[build]
command = "npm install && npm run build"
cwd = "./"

# Environment variables (if needed)
[env.production.vars]
NODE_ENV = "production"
